spring:
  profiles:
    active: local
    include: local, real
  jpa:
    show_sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
        storage_engine: innodb
    generate-ddl: true
    hibernate:
      ddl-auto: update

