spring:
  config:
    activate:
      on-profile: local
    location: application-local.yml
    #local칸
---
spring:
  config:
    activate:
      on-profile: real
    location: application-real.yml

t: abcd