spring:
  profiles:
    active: local
    include: local, real
  jpa:
    show_sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
        storage_engine: innodb
    generate-ddl: true
    hibernate:
      ddl-auto: update

#driver-class-name: com.mysql.cj.jdbc.Driver
#  url: jdbc:mysql://localhost:1234/example?serverTimezone=UTC&characterEncoding=UTF-8